# Version 0.0.1
FROM node:10-alpine
MAINTAINER hjltu <hjltu@ya.ru>
RUN apk update \
    && apk add mosquitto mosquitto-clients curl make g++ gcc
# nodejs
RUN apk --no-cache add npm avahi avahi-compat-libdns_sd avahi-dev
RUN npm install -g homekit2mqtt --unsafe-perm
# node-red
RUN npm install -g node-red --unsafe-perm
RUN mkdir -p /root/.node-red
WORKDIR /root/.node-red
RUN npm install -g node-red-dashboard \
    node-red-contrib-sonos node-red-contrib-knx
WORKDIR /root
CMD ["homekit2mqtt",]
