# Version: 0.0.1
FROM alpine
MAINTAINER hjltu <hjltu@ya.ru>
RUN apk update \
    && apk add --no-cache git mosquitto mosquitto-clients \
    curl make g++ gcc libgcc openssl
# python3
RUN apk --no-cache add py3-setuptools py3-psutil \
    && pip3 install paho-mqtt
COPY ./hjconnect /root/hjconnect
COPY ./setup /root/setup
WORKDIR /root/hjconnect
CMD [ "python3", "hjconnect.py" ]
