# Version 0.0.1
FROM node:10-alpine
MAINTAINER hjltu <hjltu@ya.ru>
RUN apk update \
    && apk add curl make g++ gcc
# node-red
RUN apk --no-cache add npm avahi avahi-compat-libdns_sd avahi-dev
RUN npm install -g homekit2mqtt --unsafe-perm
COPY ./setup /root/setup
WORKDIR /root
CMD ["homekit-start.sh"]
