version '3'

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}

services:
    hjmqtt:
      image: hjhome
      container_name: hjmqtt
      build:
        context: .
        dockerfile: Dockerfile.hj
      networks:
        - host
      volumes:
        - ./hjmqtt:/root/hjmqtt
        - ./setup:/root/setup
        - ./config:/root/config
        - ./instance:/root/instance
      command: ["cd", "/root/hjmqtt", "&&", "python3", "hjmqtt.py"]

    hjhomekit:
      image: hjhome
      container_name: hjhomekit
      build:
        context: .
        dockerfile: Dockerfile.hj
      networks:
        - host
      volumes:
        - ./hjhomekit:/root/hjhomekit
        - ./setup:/root/setup
        - ./config:/root/config
        - ./instance:/root/instance
      command: ["cd", "/root/hjhomekit", "&&", "python3", "homekit-start.py"]

    hjnode-red:
      image: hjhome
      container_name: hjnode-red
      build:
        context: .
        dockerfile: Dockerfile.hj
      networks:
        - host
      ports:
      volumes:
        - ./setup:/root/setup
        - ./config:/root/config
      command: ["node-red"]

    hjsite:
      image: hjhome
      container_name: hjsite
      build:
        context: .
        dockerfile: Dockerfile.hj
      networks:
        - default
      ports:
        - "5000:5000"
      volumes:
        - ./hjsite:/root/hjsite
        - ./setup:/root/setup
        - ./config:/root/config
        - ./instance:/root/instance
      command: ["cd", "/root/hjsite", "&&", "python3", "app.py"]

    hjconnect:
      image: hjhome
      container_name: hjconnect
      build:
        context: .
        dockerfile: Dockerfile.hj
      networks:
        - host
      volumes:
        - ./hjconnect:/root/hjconnect
        - ./setup:/root/setup
        - ./config:/root/config
        - ./instance:/root/instance
        - ./share:/root/share
      command: ["cd", "/root/hjconnect", "&&", "python3", "hjconnect.py"]

