version '3'

services:
    hjmqtt:
      image: hjmqtt
      container_name: hjmqtt
      build:
        context: .
        dockerfile: Dockerfile.hjmqtt
      restart: always
      volumes:
        - ./config:/root/config
      depends_on:
        - "hjhomekit"

    hjhomekit:
      image: hjhomekit
      container_name: hjhomekit
      build:
        context: .
        dockerfile: Dockerfile.hjhomekit
      restart: always
      networks:
        - host
      volumes:
        - ./config:/root/config
        - ./instance:/root/instance

    hjnode-red:
      image: hjnode-red
      container_name: hjnode-red
      build:
        context: .
        dockerfile: Dockerfile.hjnode-red
      restart: always
      ports:
        - "1880:1880"
      volumes:
        - ./config:/root/config

    hjsite:
      image: hjsite
      container_name: hjsite
      build:
        context: .
        dockerfile: Dockerfile.hjsite
      restart: always
      ports:
        - "5000:5000"
      volumes:
        - ./config:/root/config
        - ./instance:/root/instance

    hjconnect:
      image: hjconnect
      container_name: hjconnect
      build:
        context: .
        dockerfile: Dockerfile.hjconnect
      restart: always
      volumes:
        - ./config:/root/config
        - ./instance:/root/instance
        - ./share:/root/share

