# Version 0.0.1
FROM node:10-alpine
MAINTAINER hjltu <hjltu@ya.ru>
RUN apk update \
    && apk add npm curl make g++ gcc
# node-red
RUN npm install -g node-red --unsafe-perm
RUN mkdir -p /root/.node-red
WORKDIR /root/.node-red
RUN npm install -g node-red-dashboard \
    node-red-contrib-sonos node-red-contrib-knx
COPY ./setup/ /root/setup
COPY ./hjnode-red/ /root/hjnode-red
WORKDIR /root/hjnode-red
CMD ["sh", "node-red-start.sh"]
