# Version: 0.0.1
FROM alpine
MAINTAINER hjltu <hjltu@ya.ru>
RUN apk update \
    && apk add mosquitto mosquitto-clients \
    curl make g++ gcc libgcc openssl
# python3
RUN apk --no-cache add py3-setuptools py3-psutil \
    && pip3 install paho-mqtt flask \
    && pip3 install --upgrade werkzeug==0.15.2
COPY ./hjmqtt /root/hjmqtt
COPY ./setup /root/setup
WORKDIR /root/hjmqtt
CMD [ "python3", "hjmqtt.py" ]
